name: Send Weekly Email Report

on:
  schedule:
    # Svakog ponedeljka u 08:00 AM UTC
    - cron: '0 8 * * 1'
  workflow_dispatch:

jobs:
  send-email-report:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Run Weekly Email Script
        env:
          EMAIL_SENDER: ${{ secrets.EMAIL_SENDER }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          EMAIL_RECEIVER: ${{ secrets.EMAIL_RECEIVER }}
        run: python weekly_report.py
